name: Bug Report
description: Report non-working functionality
body:
  - type: input
    attributes:
      label: Plugin version
      description: Please specify the version of the plugin you are using.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: PHP version
      description: Please specify the version of PHP you are using.
      placeholder: 8.3.13
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel version
      description: Please specify the version of Laravel you are using.
      placeholder: 12.10.0
    validations:
      required: true
  - type: input
    attributes:
      label: Filament version
      description: Please specify the version of Filament you are using.
      placeholder: 3.3.10
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please describe in detail the problem you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        ⚠️ This is the most important part of the message. ⚠️
        Without the ability to easily reproduce your issue, it is unlikely that we will be able to assist you and work on a fix.
        Please take the time to show us the code and/or configuration needed for others to easily reproduce the issue.
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: |
        Optional: only if you have suggestions for correction/reason for the error.
        Feel free to create a pull request with your solution, it will help to get feedback faster.
